"""add reminder_sent_at column to Invoice model

Revision ID: 53a4933a3765
Revises: 39e9906fe534
Create Date: 2026-04-21 19:30:02.139423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a4933a3765'
down_revision: Union[str, Sequence[str], None] = '39e9906fe534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'reminder_sent_at')
    # ### end Alembic commands ###
